pipeline {
    agent any

    environment {
        // Docker Hub credentials ID in Jenkins
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-creds')
        IMAGE_NAME = "santhosh7896/demo-app"
        IMAGE_TAG = "latest" // you can also use build number: "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                git(
                    url: 'https://github.com/santhosh7896/jenkins-docker-k8s-demo.git',
                    credentialsId: 'github-credentials',
                    branch: 'master'
                )
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                    docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f jenkins-docker-k8s-demo/Dockerfile jenkins-docker-k8s-demo/
                """
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh """
                    echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                // Example: kubectl apply
                sh 'kubectl apply -f k8s/deployment.yaml'
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Check Docker Hub for ${IMAGE_NAME}:${IMAGE_TAG}"
        }
    }
}

